#pragma config(Motor,  port2,           motorOne,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           motorTwo,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           motorThree,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           motorFour,     tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	startMotor(motorOne, 70);
	startMotor(motorTwo, 70);
	startMotor(motorThree, 70);
	startMotor(motorFour, 70);
	wait(1);
	stopMotor(motorOne);
	stopMotor(motorTwo);
	stopMotor(motorThree);
	stopMotor(motorFour);
}
