#pragma config(Motor,  port2,           backRight,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           frontLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           frontRight,    tmotorVex393HighSpeed_MC29, openLoop)
//right motors are reversed

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
	while(true){
		motor[frontRight] = -vexRT[Ch2];
		motor[backRight] = -vexRT[Ch2];
		motor[frontLeft] = vexRT[Ch3];
		motor[backLeft] = vexRT[Ch3];
	}
}
